name: Test Echo App Server for Windows

on:
  pull_request:
  push:
    branches: [main, dev]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --include=dev --no-audit --no-fund
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
